### ISSUE TITLE
big map bug

### ISSUE THREAD

**Issue by maxcamorra** [nightowlsrp/cosmo_hud#2]
![image](https://user-images.githubusercontent.com/78707245/129406480-b711e34f-0481-421e-91c3-855d3bb95e1f.png)

**Comment by ModernAesthetics** [comment]
You are probably using Linden Threads that causes this.

**Comment by maxcamorra** [comment]
What exactly you mean?

**Comment by nightowlsrp** [comment]
It's not the HUD itself, it's caused by either LindenThreads or some other script.

**Comment by maxcamorra** [comment]
> It's not the HUD itself, it's caused by either LindenThreads or some other script.

and how to fix it? because i think you also use linden or not?
